GET http://localhost:3000/grads/
###
GET http://localhost:3000/grads/4
###
POST http://localhost:3000/grads/ HTTP/1.1
//content-type: application/json

{
    "id": 0,
    "name": "Anish Koseinseng",
    "course": "CS457",
    "grade": 97
}
###
Delete http://localhost:3000/grads/4
